# Generated by Django 2.2.5 on 2020-05-31 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, max_length=10, verbose_name='性别')),
                ('age', models.FloatField(max_length=10, verbose_name='年龄')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('height', models.CharField(max_length=10, verbose_name='身高')),
                ('weight', models.CharField(max_length=10, verbose_name='体重')),
                ('waist', models.CharField(max_length=10, verbose_name='腰围')),
                ('fat', models.FloatField(max_length=10, verbose_name='体脂')),
                ('bmi', models.FloatField(max_length=10, verbose_name='BMI')),
                ('spine', models.CharField(max_length=10, verbose_name='脊椎侧弯')),
                ('leg', models.CharField(max_length=10, verbose_name='腿型')),
                ('flexibility', models.FloatField(max_length=10, verbose_name='柔韧')),
                ('coordinate', models.FloatField(max_length=10, verbose_name='协调')),
                ('balance', models.FloatField(max_length=10, verbose_name='身体平衡')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='录入者')),
            ],
            options={
                'verbose_name': '体侧信息',
                'verbose_name_plural': '学生管理',
            },
        ),
    ]
